name: Demo Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo GitHub First runner test
      - name: Print a new line
        run: |
          echo First Line
          echo Second Line
